### ISSUE TITLE
Shuffle on all titles (or albums ?)

### ISSUE THREAD

**Issue by emengd** [Sonerezh/sonerezh#69] opened 2015-03-20 21:26 UTC
Hi,

Correct me if I am wrong, but it seems to me that it is currently impossible to shuffle through the whole library from the interface. That would be a pretty nice feature, and one that most music players offer.

A special playlist "all" would be one way to make this work, though you could also have a dedicated icon, or a "add all to queue" button.

Probably a tad more complicated to implement, but shuffling through all albums would also be cool (and shuffling through a selected set  of albums even better).

**Comment by nodiscc** [comment] 2015-03-20 23:12
Duplicate of https://github.com/Sonerezh/sonerezh/issues/47 ?

**Comment by emengd** [comment] 2015-03-21 02:06
Oh, sorry, I hadn't seen that one.

**Comment by lGuillaume124** [comment] 2015-03-21 11:08
This functionality is a big headache, but essential ^^

**Comment by Niols** [comment] 2015-03-22 13:40
Randomly pick one album could already be something cool and maybe easier to implement ?

**Comment by nodiscc** [comment] 2015-03-24 22:23
@lGuillaume124 Keeping duplicate issues open may lead to brain injury. Just sayin for your own sake.

**Comment by lGuillaume124** [comment] 2015-03-25 11:01
Yes, sorry ^^

**Closed by lGuillaume124** 2015-03-25 11:01 UTC
Labels: duplicate
